version: '2'
services:
  gateway:
    image: devopsfaith/krakend:0.6.1
    ports:
    - "8080:8080"
    volumes:
    - ./krakend:/etc/krakend
  
  dashboard:
    image: grafana

  api:
    image: skomobo_server
    build: .

  influxdb:
    image: 

# production use restart always to start on startup

  # nginx:
  #   image: nginx:1.15.15-alpine
  #   volumes:
  #   - ./mysite.template:/etc/nginx/conf.d/mysite.template
  #   ports:
  #   - "8080:80"
  #   environment:
  #   - NGINX_HOST=foobar.com
  #   - NGINX_PORT=80
  #   command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
  # redis:
  #   image: redis:3.0.7-alpine

  # gateway:
  #   # image: kong/kong:1.0rc1-alpine
  #   image: treegateway/tree-gateway:3.1.5
  #   depends_on: 
  #     - redis
  #   ports:
  #     - "8000:8000"


  # skombo_server:
  #     image: skomobo_server
  #     # depends_on:
  #     #   - "postgres"
  #     environment:
  #     #   TAX_DB_IP: "postgres"
  #     #   TAX_DB_PORT: "5432"
  #     #   TAX_DB_USER: "taxonomy_user"
  #     #   TAX_DB_PWD: "thistaxonomyisthebestthingever"
  #     #   TAX_DB: "marketdata"
  #       APP_ENV: dev
  #     #   DB_IP: mongo
  #     build: 
  #       context: .
  #       dockerfile: dev.dockerfile

  #     # ports:
  #     #   - "80:80"
  #     volumes:
  #       - ./src:/go/src/github.com/Ulfasaar/skomobo_server/app