version: '3'
services:

  # just going to map each service to a host port to make things simple
  inputs:
    build: .
    volumes:
      - Compiled:/code
    ports:
      - "81:81"

  file_processor:
    build: ./dust_cleaner_client
    volumes:
      - Compiled:/code
    ports:
      - "82:82"

  dust_cleaner:
    build: ./dust_cleaner
    volumes:
      - dust_cleaner:/code
    ports:
      - "9999:9999"
  
volumes:
  dust_cleaner:
  Compiled: