version: '3'
services:

  # just going to map each service to a host port to make things simple
  inputs:
    build:
    ports:
      - "81:81"
      
  file_processor:
    build:
    ports:
      - "82:82"

  dust_cleaner:
    build:
    ports:
      - "9999:9999"
  
