# Generated by Haxe 3.4.4
# coding: utf-8

import joblib as Joblib


class Main:
    __slots__ = ()

    @staticmethod
    def main():
        pm10Model = Joblib.load("PM10Model.pkl")
        outlierDetectorPM10 = Joblib.load("outlierDetectorPM10.pkl")
        pm2_5Model = Joblib.load("PM2_5Model.pkl")
        outlierDetectorPM2_5 = Joblib.load("outlierDetectorPM2_5.pkl")
        dust_vals = [[2, 1]]
        print(str(python_internal_ArrayImpl._get(pm10Model.predict(dust_vals), 0)))


class python_internal_ArrayImpl:
    __slots__ = ()

    @staticmethod
    def _get(x,idx):
        if ((idx > -1) and ((idx < len(x)))):
            return x[idx]
        else:
            return None



Main.main()